# Generated by Django 3.1 on 2020-08-23 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_libros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libros',
            old_name='Autor',
            new_name='autor',
        ),
    ]
